global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
    tls_config:
      insecure_skip_verify: true
