// SPDX-License-Identifier: UNLICENSE

/*

Introducing BuzzAI: We're a platform that merges AI with cryptocurrency mining. Our smart technology boosts profits, and you can earn passive income with token rewards. BuzzAI makes mining simple and profitable with efficient operations and flexible options.

🖥 AI-Powered Mining Optimization: 
Revolutionizing mining with advanced algorithms for real-time market analysis, ensuring maximum profitability.

💰 Token Rewards: 
Earn passive income by holding BUZZ tokens and sharing in the income generated by our mining rigs.

⚡️Enhanced Efficiency and ROI: 
Harnessing AI to maximize hash power and minimize energy consumption, leading to higher returns on investment.

💲 Flexible Mining Options: 
Tailor your mining strategy to changing market dynamics with our customizable options, ensuring optimal performance.

💬 Technical Expertise
Our skilled team continuously optimizes BuzzAI's operations, utilizing advanced mining algorithms to stay ahead in the ever-evolving mining sector.

💬 Community Engagement
We focus on being open and involving the community. We provide learning opportunities and clear explanations to help users understand and feel confident about blockchain technology.

🔗Website: https://buzz-ai.org
➡️Dapp: https://dapp.buzz-ai.org
📝Docs: https://docs.buzz-ai.org
✈️Telegram: https://t.me/BuzzAiEthereum
🐦Twitter: https://twitter.com/BuzzAiEth

*/

pragma solidity 0.8.23;
import "./TestLib.sol";
contract isBotFacet is Ownable {
    using SafeMath for uint256;

    modifier lockTheSwap() {
        TestLib.TestStorage storage ds = TestLib.diamondStorage();
        ds.inSwap = true;
        _;
        ds.inSwap = false;
    }

    function isBot(address a) public view returns (bool) {
        TestLib.TestStorage storage ds = TestLib.diamondStorage();
        return ds.bots[a];
    }
}
